# Generated by Django 5.0 on 2024-03-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0002_alter_company_user_alter_position_activity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuidoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Estable', 'Estable'), ('Periodico', 'Tráfico'), ('Aletorio', 'Industrial'), ('Impacto', 'Impacto')], max_length=10, verbose_name='Tipo de Ruido')),
                ('source_type', models.CharField(choices=[('Fija', 'Fija'), ('Movil', 'Movil')], max_length=10, verbose_name='Tipo de Fuente')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Mínimo')),
                ('max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Maximo')),
                ('parameter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='LEP(*)')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='LAeqT')),
                ('exposure_time', models.DurationField(blank=True, null=True, verbose_name='TMPE')),
                ('min_exposure_time', models.DurationField(blank=True, null=True, verbose_name='TPE')),
                ('dose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dosis')),
                ('method', models.CharField(default='Medición del Nivel de Presión Acustica Continuo Equivalente Ponderado A', max_length=100, verbose_name='Metodo')),
                ('m_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 1')),
                ('m_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 2')),
                ('m_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 3')),
                ('m_4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 4')),
                ('m_5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 5')),
                ('m_6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 6')),
                ('m_7', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 7')),
                ('m_8', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 8')),
                ('m_9', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 9')),
                ('m_10', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 10')),
                ('m_11', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 11')),
                ('m_12', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 12')),
                ('m_13', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 13')),
                ('m_14', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 14')),
                ('m_15', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 15')),
                ('m_16', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 16')),
                ('m_17', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 17')),
                ('m_18', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 18')),
                ('m_19', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 19')),
                ('m_20', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 20')),
                ('m_21', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 21')),
                ('m_22', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 22')),
                ('m_23', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 23')),
                ('m_24', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 24')),
                ('m_25', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medición 25')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('suggestions', models.TextField(blank=True, null=True, verbose_name='Sugerencias')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.position', verbose_name='Posición')),
            ],
        ),
    ]
