# Generated by Django 5.0 on 2024-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruido', '0002_alter_ruidoevaluation_exposure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruidoevaluation',
            name='min_exposure_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='TPE (horas)'),
        ),
    ]
