# Generated by Django 5.0 on 2024-03-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilupt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingevaluation',
            name='parameter',
            field=models.IntegerField(choices=[(50, '50'), (100, '100'), (300, '300'), (750, '750'), (3000, '3000+')], verbose_name='Parámetro'),
        ),
    ]
