# Generated by Django 5.0 on 2024-01-16 15:01

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.CharField(max_length=300, verbose_name='Direccion')),
                ('department', models.CharField(choices=[('cochabamba', 'Cochabamba'), ('la_paz', 'La Paz'), ('santa_cruz', 'Santa Cruz'), ('tarija', 'Tarija'), ('oruro', 'Oruro'), ('beni', 'Beni'), ('pando', 'Pando'), ('tarija', 'Tarija'), ('potosi', 'Potosi')], max_length=200, verbose_name='Departamento')),
                ('sector', models.CharField(max_length=200, verbose_name='Sector')),
                ('image', models.ImageField(default='null', upload_to='companies', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Area')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.company')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Puesto')),
                ('activity_type', ckeditor.fields.RichTextField(max_length=200, verbose_name='Tipo de Actividad')),
                ('image', models.ImageField(default='null', upload_to='', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.area')),
            ],
            options={
                'verbose_name': 'Puestos de Trabajo',
                'verbose_name_plural': 'Puestos de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
    ]
